apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: api-ocp-ankersen-dev-certificate
  namespace: openshift-config
spec:
  commonName: api.ocp.ankersen.dev
  dnsNames:
    - "api.ocp.ankersen.dev" 
  secretName: api-ocp-ankersen-dev-tls
  isCA: false
  privateKey:
    algorithm: ECDSA
    rotationPolicy: Always
    size: 384
  issuerRef:
    group: cert-manager.io
    name: letsencrypt-cluster-issuer
    kind: ClusterIssuer