apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-monitoring-config
  namespace: openshift-monitoring
data:
  config.yaml: |
    enableUserWorkload: false
    metricsServer:
      nodeSelector:
        node-role.kubernetes.io/infra: ''
      tolerations:
        - key: "node.ocs.openshift.io/storage"
          operator: "Equal"
          value: "true"
          effect: "NoSchedule"
    alertmanagerMain:
      volumeClaimTemplate:
       spec:
         storageClassName: lvms-vg1
         resources:
           requests:
             storage: 1Gi
