apiVersion: machineconfiguration.openshift.io/v1
kind: MachineConfig
metadata:
  name: 05-master-cpufreq-systemd-unit-machineconfig
  labels:
    machineconfiguration.openshift.io/role: master
spec:
  config:
    ignition:
      version: 3.4.0
    systemd:
      units:
        - name: cpufreq-conservative.service
          enabled: true
          contents: |
            [Unit]
            Description=Change CPU governor to conservative
            After=systemd-tmpfiles.service
            
            [Service]
            Type=simple
            ExecStart='/bin/echo conservative | tee /sys/devices/system/cpu/cpu*/cpufreq/scaling_governor'