apiVersion: nmstate.io/v1
kind: NodeNetworkConfigurationPolicy
metadata:
  name: br1-eth1-policy 
spec:
  desiredState:
    interfaces:
      - name: br1 
        description: Linux bridge with eth1 as a port 
        type: linux-bridge 
        state: up 
        ipv4:
          enabled: true
        ipv6:
          enabled: true 
        bridge:
          options:
            stp:
              enabled: false 
          port:
            - name: eth1 
