apiVersion: v1
kind: PersistentVolume
metadata:
  name: okd-image-registry-pv
spec:
  storageClassName: nfs-storage
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: /volume1/okd-image-registry
    server: brixton.ankersen.dev 
