apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: okd-image-registry-pvc
  namespace: openshift-image-registry
spec:
  storageClassName: nfs-storage
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  resources:
    requests:
      storage: 100Gi
